CREATE TABLE IF NOT EXISTS `pending_receive_entry` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `part_id` INT NOT NULL,
  `batch_number` VARCHAR(100) NOT NULL,
  `weight_g` DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
  `piece_weight_g` DECIMAL(10,4) DEFAULT NULL,
  `qty` INT NOT NULL DEFAULT 0,
  `touch_pct` DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
  `note` TEXT DEFAULT NULL,
  `stamp_id` INT DEFAULT NULL,
  `created_by` VARCHAR(150) DEFAULT NULL,
  `status` ENUM('pending','used','cancelled') NOT NULL DEFAULT 'pending',
  `linked_part_order_id` INT DEFAULT NULL,
  `linked_receive_id` INT DEFAULT NULL,
  `used_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `idx_pending_receive_status` (`status`),
  INDEX `idx_pending_receive_part` (`part_id`),
  INDEX `idx_pending_receive_batch` (`batch_number`),
  INDEX `idx_pending_receive_link_order` (`linked_part_order_id`),
  CONSTRAINT `fk_pending_receive_part` FOREIGN KEY (`part_id`) REFERENCES `part`(`id`) ON DELETE RESTRICT,
  CONSTRAINT `fk_pending_receive_stamp` FOREIGN KEY (`stamp_id`) REFERENCES `stamp`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pending_receive_link_order` FOREIGN KEY (`linked_part_order_id`) REFERENCES `part_order`(`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_pending_receive_link_receive` FOREIGN KEY (`linked_receive_id`) REFERENCES `part_order_receive`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;